[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:uvicorn]
command=uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/uvicorn.log
stderr_logfile=/var/log/uvicorn.log

[program:rqworker]
command=rq worker --url %(ENV_REDIS_URL)s default
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/rqworker.log
stderr_logfile=/var/log/rqworker.log
environment=PYTHONPATH="/app"

[program:cleanup]
command=/bin/sh -c "while true; do python /app/cleanup.py; sleep 86400; done"
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/cleanup.log
stderr_logfile=/var/log/cleanup.log
environment=PYTHONPATH="/app"
